### ISSUE TITLE
Aren't taus also leptons?

### ISSUE THREAD

**Issue by ingomueller-net** [iris-hep/adl-benchmarks-index#13]
Non-physicist here ;)

According to Wikipedia ([here](https://en.wikipedia.org/wiki/Lepton) and [here](https://en.wikipedia.org/wiki/Tau_(particle))), taus are leptons. However, none of the query implementations uses the `Tau_*` branches of the data set for Q7 and Q8. Out of curiousity: why is that?

**Comment by masonproffitt** [comment]
Yeah, this is part of annoying HEP experiment terminology where "lepton" often just implies "electron or muon" since taus can look much more like jets. (I didn't write the text of these challenges.) A more accurate term is "light lepton", which I doubt anyone would be opposed to switching to. And maybe a footnote for non-HEP people specifying that this means "electron or muon".
