### ISSUE TITLE
Document origin of the benchmark data

### ISSUE THREAD

**Issue by ingomueller-net** [iris-hep/adl-benchmarks-index#15]
What is the original dataset that the benchmark data was "converted from"? This one: http://opendata.cern.ch/record/6021? How was it converted? (The one that I linked is about 1000 times larger than the benchmark data.)

**Comment by masonproffitt** [comment]
This came from [Stefan Wunsch](https://github.com/stwunsch) (<https://groups.google.com/g/hsf-analysis-wg/c/U5fdT9uXEJI/m/P3JIpaoVCAAJ>), so he would be the one to ask here.

**Comment by gordonwatts** [comment]
Has anyone reached out to Stefan? I can't tell if he has a username here on github (probably, but I can't figure it out).

**Comment by masonproffitt** [comment]
His username is @stwunsch.

**Comment by stwunsch** [comment]
Hi!
So the tool to convert the data can be found here: http://opendata.web.cern.ch/record/12340 
I don't fully recall which dataset is used here exactly, but the one you've pointed out seems to be correct. Most likely I've processed not all of the parked dataset, because it's a pretty large one.
If you don't want to rerun the conversion to NanoAOD-like data and you are looking for other, potentially larger, datasets, you can also take some from the example analysis here: http://opendata.web.cern.ch/record/12350

**Comment by stwunsch** [comment]
Ah well, I can tell, because I had copied the filelists from the CERN Open Data portal into the repository with the AOD to NanoAOD conversion tool. You can find the filelists here: https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/tree/master/data
So it is `CMS_Run2012B_SingleMu_AOD_22Jan2013-v1`, the one you have pointed out.
This also means that you can "just" run the code as it is. The best starting point is commenting in the dataset here (https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/submit_jobs.sh) and then following the  script, or the instructions in the readme.

**Comment by gordonwatts** [comment]
Thanks! @masonproffitt - should we add this as documentation on this website somewhere?

**Comment by masonproffitt** [comment]
> @masonproffitt - should we add this as documentation on this website somewhere?

Yep, I just made a PR to add it (#17).
