### ISSUE TITLE
Update link to "more official" RDataFrame implemention and check results

### ISSUE THREAD

**Issue by ingomueller-net** [iris-hep/adl-benchmarks-index#25]
There is now an implementation of this benchmark in the [ROOT repository](https://github.com/stwunsch/rootbench/blob/master/root/tree/dataframe/RDataFrameOpenDataBenchmarks.cxx). Interestingly, it consists of two different implementations: one that uses jitted code (from the strings passed into `Filter`, `Define`, etc), one that uses statically compiled code (from lambda functions passed into `Filter`, `Define`, etc). The latter seems to be 3x [faster](https://root-forum.cern.ch/t/scalability-of-rdataframes-on-16-cores/44222/44).

Should we update the link of the RDataFrame implementation to point to that one?

If so, I think it would be a good idea to also check correctness. There are several [unaddressed issues](https://github.com/stwunsch/opendata-benchmarks/issues) in the original repo, which may or may not have been addressed in the official ROOT repo; plus, we encountered a few other issues with the other implementations, which may be present in the RDataFrame version as well.

**Comment by ingomueller-net** [comment]
BTW: [this](https://github.com/root-project/rootbench/pull/219) is the PR that added the benchmarks.

**Comment by masonproffitt** [comment]
Well, it's not quite "the" ROOT [repository](https://github.com/root-project/root), but it is an official ROOT project team repository.

I can already see that it has the same issues that I needed to correct in my RDF implementation, so we'd certainly need to address those as you said. The other issue is that the rootbench repository has a different focus from this one. There, "benchmark" only refers to performance, whereas here the focus is on demonstrating functionality and readability. The idea for this repository is to show code that is representative of what an analysis user might actually write. No one doing a physics analysis would write code like that in the rootbench repo, so I don't think it makes sense to link directly to it.

My preference would be to ask Stefan to review my corrected version and use that one (either directly from my repo or with the corrections propagated to the original repo), since that one has now been thoroughly verified.

**Comment by ingomueller-net** [comment]
OK, I see. I guess the main difference between that implementation and "what a physicist would write" is the orchestration, i.e., the organization into test cases, etc, not the "actual analysis", i.e., the chain of `.Define(...)` and `.Filter(...)` expressions, etc, right?

So yes, pointing to your corrected version, plus incorporating feedback if there is any sounds good to me. How about the "compiled" version? Should we extend our implementations by such a variant?

**Comment by masonproffitt** [comment]
I was actually referring to the code specifically in the rootbench repository that you linked (because it has all kind of references to numbers of threads and debug macros), but the code in <https://github.com/root-project/opendata-benchmarks> looks "normal" enough to me, other than the places where the implementation is just incorrect (like using `MET_sumet` instead of `MET_pt`).

Is there a reason to have a separate "compiled" version if we allow compilation of the macros with `.L macro.C+O`? Is there a difference? Based on the ROOT forum discussion, it seems like there isn't?

**Comment by ingomueller-net** [comment]
I think there is. There are two potential levels of compilation: the macros and the arguments to RDataFrame primitives such as `Filter()`. For the latter, it is possible to specify strings, which are then Just-in-Time compiled, independantly of whether the surrounding macro has been optimized or not.

**Comment by masonproffitt** [comment]
Ah, so what we're really talking about jitted vs. non-jitted. That difference might be important for the performance comparisons that you're doing, but I think it's beyond the scope of these functionality benchmarks.

**Comment by ingomueller-net** [comment]
Indeed, I think that this trade-off space between user-friendliness and performance is interesting, and the jitted vs non-jitted options of RDataFrames offer two different trade-offs. I thought that that was also part of your goals or is performance not relevant?

**Comment by masonproffitt** [comment]
Performance is definitely not the primary focus--the most important things that these implementations are supposed to demonstrate is the fact that a task can be expressed in a particular ADL and how easy it is to write it (more or less the level of readability).

In terms of whether execution time matters, it depends on what kind of improvement we're talking about. Differences on the order of 10% are negligible for our purposes here, but an optimized version that runs 10x faster may well be significant enough to warrant a separate entry.
