### ISSUE TITLE
Revised coffea benchmark

### ISSUE THREAD

**Issue by nsmith-** [iris-hep/adl-benchmarks-index#30]
If @mat-adamec agrees, I propose to switch the coffea benchmark link to the jupyter notebook https://github.com/nsmith-/coffea-benchmarks/blob/master/coffea-adl-benchmarks.ipynb which has generally more straightforward and verified results for the tasks. On the other hand, it does not introduce coffea syntax pedagogically.

**Comment by mat-adamec** [comment]
I have no objections to this. These queries all live on in coffea-casa (https://github.com/CoffeaTeam/coffea-casa-tutorials), where the pedagogy is more useful anyways. Perhaps it might be good to include a link over there in the readme, so that people who do want a more explanatory introduction know where to go?

**Comment by mat-adamec** [comment]
This can be closed now that https://github.com/iris-hep/adl-benchmarks-index/pull/31 is merged.
